# Site settings
title: Enterin tietoiskupankki
description: "Tietokanta, jonka tarkoituksena on helpottaa aineistojen löytämistä Enterin esitelmäkokoelmasta."
baseurl: "/jekyll-for-designers" 
url: "http://jameswillweb.github.io/jekyll-for-designers" 
tagline: Opas oikean tiedon äärelle

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
